question_data = [
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "text": "Linus Torvalds created Linux and Git.", "answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "text": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
                      "answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "text": "Pointers were not used in the original C programming language; they were added later on in C++.",
                      "answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "text": "RAM stands for Random Access Memory.", "answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "text": "Ada Lovelace is often considered the first computer programmer.",
                      "answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "text": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
                      "answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "text": "Time on Computers is measured via the EPOX System.", "answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "text": "The Windows 7 operating system has six main editions.",
                      "answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "text": "The Windows ME operating system was released in the year 2000.",
                      "answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science: Computers",
                      "type": "boolean",
                      "difficulty": "easy",
                      "text": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
                      "answer": "False", "incorrect_answers": ["True"]}]
